### ISSUE TITLE
Pretty-printing of target triples

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/llvm-pretty#100]
#96 added support for parsing target triples, it remains to print them.

**Comment by RyanGlScott** [comment]
I might be missing something, but doesn't [`Text.LLVM.Triple.Print`](https://github.com/elliottt/llvm-pretty/blob/abe6943985fe88a7d1b993057c47e49d3cc67bb3/src/Text/LLVM/Triple/Print.hs) provide pretty-printing functionality for target triples?

**Comment by langston-barrett** [comment]
It provides all the functionality we need, but it was not yet wired into `ppModule`, see https://github.com/elliottt/llvm-pretty/pull/101
