### ISSUE TITLE
Label targets are not represented correctly for llvm-as consumption

### ISSUE THREAD

**Issue by kquick** [GaloisInc/llvm-pretty#114]
Bitcode generated by clang and then parsed via llvm-pretty-bc-parser and then output via this library into `.ll` files may not be usable with `llvm-as` because of the representation of the label targets.

Generated code contains `call void @llvm.db.label(metadata !DILabel(scope: !8, name: loop,` which fails on `loop` (presumably because it needs to be quoted).

This error can be seen running `cabal run disasm-test -- -p '/callbr.c/' (requires https://github.com/galoisinc/llvm-pretty-bc-parser/pulls/230).

**Comment by kquick** [comment]
[From Ryan Scott:]

OK, I've extracted a test case that confirms that this is in fact an `llvm-pretty` pretty-printer issue:

```c
// callbr.c
int main(void) {
  int cond = 0;
  asm volatile goto("testl %0, %0; jne %l1;"
                    : /* No outputs */
                    : "r"(cond)
                    : /* No clobbers */
                    : label_true, loop);
  return 0;
loop:
  return 0;
label_true:
  return 1;
}
```

First, note how LLVM itself formats `DILabel`s:

```
$ clang -S -emit-llvm -g -O0 callbr.c -o callbr.ll
$ cat callbr.ll | grep "DILabel"
!17 = !DILabel(scope: !7, name: "loop", file: !1, line: 14)
!20 = !DILabel(scope: !7, name: "label_true", file: !1, line: 16)
```

Now note how it appears after round-tripping through `llvm-pretty`:

```hs
-- Main.hs
module Main (main) where

import Data.LLVM.BitCode
import Text.LLVM.PP

main :: IO ()
main = do
  res <- parseBitCodeFromFile "callbr.bc"
  case res of
    Left err -> fail $ formatError err
    Right bc -> print $ ppLLVM38 ppModule bc
```

Running this program after compiling with `clang -c -emit-llvm -g -O0 callbr.c -o callbr.bc` gives:

```
  call void @llvm.dbg.label(metadata !DILabel(scope: !7, name: loop,
  ...
  call void @llvm.dbg.label(metadata !DILabel(scope: !7,
                                              name: label_true,
```

Which lacks double quotes around the `name` values.

**Comment by RyanGlScott** [comment]
I've opened #115, which I believe should address this. Can you give it a try, @kquick?

**Comment by kquick** [comment]
This does seem to fix those issues (in conjunction with the llvm-pretty-bc-parser adaptation on https://github.com/GaloisInc/llvm-pretty-bc-parser/pull/233), but runs into another one: #116
