### ISSUE TITLE
Global variable declarations incorrect

### ISSUE THREAD

**Issue by kquick** [GaloisInc/llvm-pretty#123]
When using clang for any LLVM version starting with 11, the pretty-printed output for global variable declarations is incorrect and fails `llvm-as` assembly.

**Comment by kquick** [comment]
For more information, see https://github.com/GaloisInc/llvm-pretty-bc-parser/pull/243

**Comment by RyanGlScott** [comment]
Per https://github.com/elliottt/llvm-pretty/issues/128#issuecomment-1732689095, closing as a duplicate of #128.
