### ISSUE TITLE
`llvm-as` fails on `@val = external default global i32 123`

### ISSUE THREAD

**Issue by kquick** [GaloisInc/llvm-pretty#128]
Testing shows that the LLVM Project `llvm-as` assembler does not accept either `external` or `default` for these declarations.  It accepts: `@val = global i32 123`.

**Comment by RyanGlScott** [comment]
What is the relationship between this issue and https://github.com/elliottt/llvm-pretty/issues/123?

**Comment by kquick** [comment]
This is likely a duplicate of #123.
