### ISSUE TITLE
Parse/print target triples

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/llvm-pretty#21]
Does llvm-pretty have the ability to represent target triples?  A glance through the AST doesn't show any obvious place where that information is captured.  It would be nice to be able to parse and print the target triple information.  In particular, I'd like to be able to know the architecture the code was compiled for when reading bit code via llvm-pretty-bc-parser.

**Comment by elliottt** [comment]
It doesn't currently, but that would be an easy addition. You could implement it much the same way as data layout is now.

**Comment by langston-barrett** [comment]
I've started work on this, branch available here: https://github.com/siddharthist/llvm-pretty/tree/target-triple

**Comment by langston-barrett** [comment]
I've started working on this... again... https://github.com/langston-barrett/llvm-pretty/tree/lb/triple
