### ISSUE TITLE
Upload new release(s) to Hackage

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/llvm-pretty#26]
llvm-pretty-bc-parser's master branch [depends on](https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/master/llvm-pretty-bc-parser.cabal#L61) llvm-pretty version 0.7.3, which [isn't yet on hackage](http://hackage.haskell.org/package/llvm-pretty).

**Comment by elliottt** [comment]
It looks like there aren't any breaking changes since 0.7.2 (which also wasn't released). Is there anything else you'd like to go into 0.7.3 before it's uploaded?

**Comment by langston-barrett** [comment]
Perhaps #28! Thanks!

**Comment by elliottt** [comment]
OK, I've (finally) merged in #28, is there anything else you'd like merged in before a release?

**Comment by langston-barrett** [comment]
Not that I can think of. Thanks!
