### ISSUE TITLE
Pretty-printing the source filename

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/llvm-pretty#30]
The AST [has a place](https://github.com/elliottt/llvm-pretty/blob/master/src/Text/LLVM/AST.hs#L39) for a `source_filename`:
```haskell
data Module = Module
  { modSourceName :: Maybe String
```
But `ppModule` [doesn't seem to use it](https://github.com/elliottt/llvm-pretty/blob/master/src/Text/LLVM/PP.hs#L78):
```haskell
ppModule :: LLVM => Module -> Doc
ppModule m = foldr ($+$) empty
  $ ppDataLayout (modDataLayout m)
  : ppInlineAsm  (modInlineAsm m)
  : concat [ map ppTypeDecl    (modTypes m)
           , map ppGlobal      (modGlobals m)
           , map ppGlobalAlias (modAliases m)
           , map ppDeclare     (modDeclares m)
           , map ppDefine      (modDefines m)
           , map ppNamedMd     (modNamedMd m)
           , map ppUnnamedMd   (modUnnamedMd m)
           , map ppComdat      (Map.toList (modComdat m))
           ]
```

**Comment by elliottt** [comment]
Ah, was `llvm-disasm` choosing how to print out the module id, when it should be handled by `llvm-pretty`'s rendering code?

**Comment by langston-barrett** [comment]
`llvm-disasm` always uses `ppModule`: https://github.com/siddharthist/llvm-pretty-bc-parser/blob/readme/llvm-disasm/LLVMDis.hs#L115

So the issue is that `source_filename` isn't appearing in the disassembled, textual output.
